### ISSUE TITLE
should be able to rate and review together

### ISSUE THREAD

**Issue by AzCI1** [WillowMT/csit314#45]
The ui is already correct, but both the submit buttons should submit both rating and review, so you can give 5 star rating and write review and click on the button beside rating, and it will save both rating and review, and if you write 5 star rating and write review and click button under text box for review, it will also save both rating and review, making them do the same thing.

**Comment by WillowMT** [comment]
Since the use cases were different, I split the two. I'll just merge the two functionality into one form.
